[options]
library = "He"
version = "1"
girs_directories = ["../gir-files", "../"]
min_cfg_version = "1"
work_mode = "sys"
external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gtk",
   "Pango",
]