name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install system level libraries
        run: sudo apt install libpango1.0-dev libgtk-4-dev libgee-0.8-dev meson ninja-build valac valadoc

      - name: Install libhelium
        run: meson build
      - name: Build libhelium with Ninja
        run: ninja
        working-directory: ./build
      - name: Install libhelium globally
        run: sudo ninja install
        working-directory: ./build

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            default: true
            components: rustfmt, clippy

      - name: Generate docs
        run: cargo install rustdoc-stripper
      - run: ./generator.py --embed-docs
      - run: cargo doc --features dox --no-deps
      - run: mv target/doc/ docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com